export const COMPANY_FILTER_FIELDS = [
  {
    field: 'company_name',
    label: 'Companhia',
    type: 'text',
    operators: ['CONTAINS', 'EQUALS', 'STARTS_WITH'],
  },
  {
    field: 'trading_name',
    label: 'Nome de pregão',
    type: 'text',
    operators: ['CONTAINS', 'EQUALS', 'STARTS_WITH'],
  },
  {
    field: 'issuing_company',
    label: 'Companhia emissora',
    type: 'text',
    operators: ['CONTAINS', 'EQUALS', 'STARTS_WITH'],
  },
  {
    field: 'cnpj',
    label: 'CNPJ',
    type: 'text',
    operators: ['EQUALS', 'CONTAINS'],
  },
  {
    field: 'cvm_code',
    label: 'Código CVM',
    type: 'text',
    operators: ['EQUALS', 'CONTAINS'],
  },
  {
    field: 'market',
    label: 'Mercado',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'industry_sector',
    label: 'Setor',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'industry_subsector',
    label: 'Subsetor',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'industry_segment',
    label: 'Segmento',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'industry_classification',
    label: 'Classificação da indústria',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'industry_classification_eng',
    label: 'Classificação (inglês)',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'company_category',
    label: 'Categoria da companhia',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'company_type',
    label: 'Tipo de companhia',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'listing_segment',
    label: 'Segmento de listagem',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'registrar',
    label: 'Escriturador',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'institution_common',
    label: 'Instituição Ordinária',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'institution_preferred',
    label: 'Instituição Preferencial',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'status',
    label: 'Status',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'market_indicator',
    label: 'Indicador de mercado',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'code',
    label: 'Código (ticker)',
    type: 'text',
    operators: ['EQUALS', 'CONTAINS', 'STARTS_WITH'],
  },
  {
    field: 'has_bdr',
    label: 'Tem BDR',
    type: 'boolean',
    operators: ['EQUALS'],
  },
  {
    field: 'type_bdr',
    label: 'Tipo de BDR',
    type: 'select',
    operators: ['IN', 'EQUALS'],
  },
  {
    field: 'has_quotation',
    label: 'Tem cotação',
    type: 'boolean',
    operators: ['EQUALS'],
  },
  {
    field: 'has_emissions',
    label: 'Tem emissões',
    type: 'boolean',
    operators: ['EQUALS'],
  },
]
