apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://metrics:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    uid: DS_LOKI
    url: http://logs-ingestion:3100
    isDefault: false
    editable: true
